/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ill.gltf --transform
Author: Defne Tuncer (https://sketchfab.com/defnetuncer98)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drink-up-alice-327aee9f75b44c9ea1b3d5029fd45c22
Title: Drink up, Alice
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ill(props) {
  const { nodes, materials } = useGLTF('/ill-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Bottle} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.DarkLiquid} scale={0.75} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.DarkLiquid} position={[0.05, 1.96, 0]} rotation={[0, 0, -0.04]} scale={[0.21, 0.2, 0.2]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Mantar} position={[0, 0, -0.09]} scale={[-0.04, 1, 1]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Drink_Up_Alice} position={[0, -1.58, 0]} rotation={[Math.PI / 2, 0, 0]} scale={[1.12, 1.12, 0.45]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Mantar} position={[0, 0, -0.09]} scale={[-0.04, 1, 1]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['BottleOutline.001']} />
    </group>
  )
}

useGLTF.preload('/ill-transformed.glb')
