/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Product.gltf --transform
Author: ivandrodejesues908 (https://sketchfab.com/ivandrodejesues908)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-max-akatsuki-b0f83707ec294bb2813e67c8c3e5db31
Title: Nike Air Max "akatsuki"
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Product(props) {
  const { nodes, materials } = useGLTF('/Product-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Product-transformed.glb')
